// <auto-generated />
namespace AE.Funny.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addedexception : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedexception));
        
        string IMigrationMetadata.Id
        {
            get { return "201504141736298_Added exception"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
